Demo Owning Type Arguments
rust-diplomat/diplomat pull request #714
Opened 2024-10-25 20:32 UTC by ambiguousname

Adds `FunctionOwningType:ParameterType` as a default way of labeling parameters.

Fixes #713, intended to fix #611 as well.

2024-10-25 21:06 UTC, Manishearth approved these changes

2024-10-28 11:16 UTC, robertbastian requested changes
I realise this wasn't clear the way I filed the issue, but I was thinking of using the parameter names, not the types. The reason is that there can be two parameters of the same type, but they would have different names.

2024-10-28 16:26 UTC, Manishearth commented
We'd maybe even want to do both

This is why I'd love for this information to be passed down to the renderer in a structured fashion: My ideal UI for this is something like this with `<fieldset>`

![image](https://github.com/user-attachments/assets/4c616874-1a1f-40f5-b522-872a5d6ba2b9)

2024-10-29 02:48 UTC, ambiguousname commented
I think that'd be fantastic! Fixes for using parameter names are in.

 I'll open an issue for adding more context in `RenderInfo` (and updating the default renderer to use `<fieldset>`)

2024-10-29 02:52 UTC, ambiguousname commented
Just one note, if the parameter is the `self` parameter, the default labeling will show up as something like `Self:ParamName`. Is that desirable? It might be less ambiguous to replace `self` with the owning type of the function.

2024-10-29 10:52 UTC, robertbastian approved these changes

2024-10-29 10:53 UTC, robertbastian commented
I think `self` if fine for now.

2024-10-29 10:53 UTC, merged